[project]
name = "phd"
version = "0.1.0"
description = "Fork of SpeechSplit2 for my PhD project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cement",
    "disvoice",
    "inflect",
    "kaldi-io",
    "librosa",
    "matplotlib",
    "more-itertools",
    "numba",
    "numpy",
    "pillow",
    "praat-parselmouth",
    "pysptk",
    "pyworld",
    "safetensors",
    "scipy",
    "setuptools-rust",
    "standard-imghdr",
    "tensorboard",
    "tiktoken",
    "tqdm",
    "types-requests",
    "unidecode",
    "wavenet-vocoder",
    "speech-intelligibility-index",
]

[project.scripts]
experiment = "phd:main"
check = "phd:check"
scratch = "phd:scratch"

[build-system]
requires = [ "setuptools" ]

[tool.uv]
managed = true
default-groups = "all"
cache-keys = [
    { file = "pyproject.toml" },
]
compile-bytecode = true
prerelease = "allow"
conflicts = [
    [
        { extra = "rocm" },
        { extra = "cuda" },
        { extra = "cpu" },
    ],
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/nightly/rocm6.4"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/nightly/cu129"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/nightly/cpu"
explicit = true

[tool.mypy]
color_output = true
explicit_package_bases = true
force_uppercase_builtins = true
ignore_missing_imports = true
pretty = true
show_column_numbers = true
show_error_context = true

[dependency-groups]
dev = [
    {include-group = "lint"},
]
lint = [
    "python-lsp-server[all]",
    "pylsp-mypy",
    "python-lsp-isort",
    "python-lsp-black",
    "pyls-memestra",
    "pylsp-rope",
    "python-lsp-ruff",
]

[project.optional-dependencies]
rocm = [
    "lightning-utilities",
    "matplotlib",
    "mypy-extensions",
    "numpy",
    "pandas",
    "pillow",
    "pytorch-triton",
    "pytorch-triton-rocm",
    "pytorch-triton-xpu",
    "safetensors",
    "setuptools",
    "tiktoken",
    "torch==2.9.0.dev20250714+rocm6.4",
    "torchaudio==2.8.0.dev20250714+rocm6.4",
    "torchmetrics",
    "torchtune",
    "torchvision",
    "tqdm",
    "typing-extensions",
    "typing-inspect",
]
cuda = [
    "lightning-utilities",
    "matplotlib",
    "mypy-extensions",
    "numpy",
    "pandas",
    "pillow",
    "pytorch-triton",
    "pytorch-triton-rocm",
    "pytorch-triton-xpu",
    "safetensors",
    "setuptools",
    "tiktoken",
    "torch",
    "torchaudio",
    "torchmetrics",
    "torchtune",
    "torchvision",
    "tqdm",
    "typing-extensions",
    "typing-inspect",
]
cpu = [
    "lightning-utilities",
    "matplotlib",
    "mypy-extensions",
    "numpy",
    "pandas",
    "pillow",
    "pytorch-triton",
    "pytorch-triton-rocm",
    "pytorch-triton-xpu",
    "safetensors",
    "setuptools",
    "tiktoken",
    "torch",
    "torchaudio",
    "torchmetrics",
    "torchtune",
    "torchvision",
    "tqdm",
    "typing-extensions",
    "typing-inspect",
]


[tool.uv.sources]
disvoice = { path = "external/disvoice", editable = true }
lightning-utilities = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
matplotlib = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
mypy-extensions = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
numpy = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
pandas = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
pillow = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
pytorch-triton = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
pytorch-triton-rocm = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
pytorch-triton-xpu = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
safetensors = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
setuptools = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
tiktoken = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
torch = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
torchaudio = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
torchmetrics = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
torchtune = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
torchvision = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
tqdm = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
typing-extensions = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
typing-inspect = [ {index = "pytorch-rocm", extra = "rocm"}, {index = "pytorch-cuda", extra = "cuda"}, {index = "pytorch-cpu",  extra = "cpu" }, ]
