[tox]
no_package = true
pip_pre = true
min_version = 4.9.0
requires =
    setuptools
    tox-ignore-env-name-mismatch~=0.2.0
    tox

[testenv:{run,mypy,reports}]
env_dir = {toxworkdir}{/}static
runner = ignore_env_name_mismatch
deps =
    mypy
    inflect
    librosa
    matplotlib
    more-itertools
    numba
    numpy<2
    pillow
    pysptk
    pyworld
    safetensors
    scipy
    setuptools-rust
    standard-imghdr
    tensorboard
    tiktoken
    torch
    torchaudio
    tqdm
    triton
    types-requests
    unidecode
    wavenet_vocoder
    {[testenv:tensorboard]deps}
setenv =
    PIP_INDEX_URL=https://download.pytorch.org/whl/nightly/rocm6.4
    PIP_EXTRA_INDEX_URL=https://pypi.org/simple
description =
    run: Run the program
    mypy: Run mypy type checks
    reports: Generate type-checking reports
commands =
    run: python . {posargs}
    mypy: mypy -p .
    reports: mypy -p . --html-report artefacts/mypy
    tensorboard: tensorboard --logdir artefacts/tensorboard #--samples_per_plugin='scalars=1600000'
