[paths]
proc_data = "/mnt/datasets/processed"
raw_data = "/mnt/datasets/raw"

[options]
bottleneck = "switch"
experiment = "trainswitch"
audio = "speechsplit2"
trace = false

[log]
level = "DEBUG"
file = true
