[paths]
proc_data = "/mnt/datasets/processed"
raw_data = "/mnt/datasets/raw"

[options]
bottleneck = "large"
experiment = "syllable_estimation"
audio = "speechsplit2"
trace = false

[log]
level = "DEBUG"
file = true
