[audio-processing]
chunk_length = 30
f0_f_hi = 600
f0_f_lo = 100
f0_m_hi = 250
f0_m_lo = 50
freq_max = 7600
freq_min = 90
hi_pass_cutoff = 30
hop_len = 256
max_len_pad = 192
n_fft = 1024
sample_rate = 16000
vtlp_fft = 2048
